# Generated by Django 2.1.7 on 2019-04-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('col_id', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('studio_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studio.Studio')),
            ],
        ),
    ]
