# Generated by Django 2.1.7 on 2019-05-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0003_auto_20190507_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
