# Generated by Django 2.1.7 on 2019-04-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='演出厅名')),
                ('seat_rows', models.IntegerField()),
                ('seat_cols', models.IntegerField()),
            ],
        ),
    ]
