# Generated by Django 2.1.7 on 2019-05-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ticket_counts', models.IntegerField()),
                ('ticket_money', models.FloatField(default=40)),
                ('play', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.Play')),
                ('studio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.Studio')),
            ],
        ),
    ]
