# Generated by Django 2.1.7 on 2019-05-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='play',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.Play'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.Studio'),
        ),
    ]
