# Generated by Django 2.1.7 on 2019-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_ticket_all_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ticket_all_counts',
            field=models.IntegerField(),
        ),
    ]
