# Generated by Django 2.1.7 on 2019-05-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_schedule'),
        ('schedule', '0004_auto_20190508_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
