# Generated by Django 2.1.7 on 2019-05-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='order',
        ),
    ]
