# Generated by Django 2.1.7 on 2019-05-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='roles',
            new_name='auths',
        ),
    ]
