# Generated by Django 2.1.7 on 2019-04-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('play_time', models.DateField()),
                ('length', models.IntegerField()),
                ('desc', models.TextField()),
                ('director', models.CharField(max_length=20)),
                ('actors', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('types', models.ManyToManyField(to='type.Type')),
            ],
        ),
    ]
