# Generated by Django 2.1.7 on 2019-05-09 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seat', '0005_remove_seat_selected'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('money', models.FloatField()),
                ('seats', models.ManyToManyField(to='seat.Seat')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.Studio')),
            ],
        ),
    ]
