# Generated by Django 2.1.7 on 2019-05-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190508_1201'),
        ('order', '0004_auto_20190509_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='order',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ticket',
        ),
        migrations.AddField(
            model_name='order',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Schedule'),
        ),
    ]
