# Generated by Django 2.1.7 on 2019-05-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190509_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='schedule',
        ),
    ]
