# Generated by Django 2.1.7 on 2019-05-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_schedule_order'),
        ('order', '0006_remove_order_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Schedule'),
        ),
    ]
